### ISSUE TITLE
Please add information about howto contribute to sqlite3

### ISSUE THREAD

**Issue by norbertfuhs** [go-sqlite/sqlite3#27]
Would you please add an CONTRIBUTING.md  or an intro in README.md how to contribute to sqlite3.
It would be nice for people new to this open source project to know howto get started.

**Comment by adamdecaf** [comment]
@norbertfuhs Good idea! How does this look for contributing? https://github.com/go-sqlite/sqlite3/pull/28

**Comment by norbertfuhs** [comment]
@adamdecaf   Thank you!
